# Generated by Django 5.2.1 on 2025-05-22 16:14

from django.db import migrations, models

def create_jornadas_laborales(apps, schema_editor):
    Jornada = apps.get_model('doctores', 'JornadasLaborales')
    Jornada.objects.bulk_create([
        Jornada(nombre='matinal', descripcion='Horario de la mañana'),
        Jornada(nombre='vespertina', descripcion='Horario de la tarde'),
    ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JornadasLaborales',
            fields=[
                ('jornada_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_jornadas_laborales),
    ]
