# Generated by Django 5.2.1 on 2025-05-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_role_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_afiliacion',
            fields=[
                ('afiliacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('afiliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.tipo_afiliacion')),
            ],
        ),
        migrations.CreateModel(
            name='historial_clinico',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('resumen_general', models.CharField(max_length=100)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
