# Generated by Django 5.2.1 on 2025-06-01 20:24

from django.db import migrations, models

def create_tipos_afiliacion(apps, schema_editor):
    TipoAfiliacion = apps.get_model('pacientes', 'TipoAfiliacion')
    TipoAfiliacion.objects.bulk_create([
        TipoAfiliacion(nombre='contributivo', descripcion='Afiliados que aportan al sistema mediante pagos mensuales.'),
        TipoAfiliacion(nombre='subsidiado', descripcion='Afiliados cubiertos por el Estado debido a su falta de ingresos.'),
        TipoAfiliacion(nombre='especial', descripcion='Personas cubiertas por regímenes especiales o entidades específicas.'),
        TipoAfiliacion(nombre='vinculado', descripcion='Usuarios registrados pero aún no afiliados formalmente.'),
    ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAfiliacion',
            fields=[
                ('afiliacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_tipos_afiliacion),
    ]
