# Generated by Django 5.2.1 on 2025-05-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateTimeField(),
        ),
    ]
