# Generated by Django 5.2.1 on 2025-05-22 16:14

import django.db.models.deletion
from django.db import migrations, models

def create_tipos_afiliacion(apps, schema_editor):
    TipoAfiliacion = apps.get_model('pacientes', 'TipoAfiliacion')
    TipoAfiliacion.objects.bulk_create([
        TipoAfiliacion(nombre='contributivo', descripcion='Afiliados que aportan al sistema mediante pagos mensuales.'),
        TipoAfiliacion(nombre='subsidiado', descripcion='Afiliados cubiertos por el Estado debido a su falta de ingresos.'),
        TipoAfiliacion(nombre='especial', descripcion='Personas cubiertas por regímenes especiales o entidades específicas.'),
        TipoAfiliacion(nombre='vinculado', descripcion='Usuarios registrados pero aún no afiliados formalmente.'),
    ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialesclinicos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.RunPython(create_tipos_afiliacion),
    ]
