# Generated by Django 5.2.1 on 2025-06-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialesClinicos',
        ),
    ]
