# Generated by Django 5.2.1 on 2025-05-21 02:26

from django.db import migrations

def create_tipos_afiliacion(apps, schema_editor):
    tipo_afiliacion = apps.get_model('pacientes', 'tipo_afiliacion')

    tipo_afiliacion.objects.bulk_create([
        tipo_afiliacion(nombre='Contributivo', descripcion='Afiliados que aportan al sistema mediante pagos mensuales.'),
        tipo_afiliacion(nombre='Subsidiado', descripcion='Afiliados cubiertos por el Estado debido a su falta de ingresos.'),
        tipo_afiliacion(nombre='Especial', descripcion='Personas cubiertas por regímenes especiales o entidades específicas.'),
        tipo_afiliacion(nombre='Vinculado', descripcion='Usuarios registrados pero aún no afiliados formalmente.'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_fecha_ingreso'),
    ]

    operations = [
        migrations.RunPython(create_tipos_afiliacion),
    ]
