# Generated by Django 5.2.1 on 2025-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_insertar_tipos_afiliacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
