# Generated by Django 5.2.1 on 2025-06-04 02:51

import django.db.models.deletion
from django.db import migrations, models

def unidades_medicas(apps, schema_editor):
    UnidadesMedicas = apps.get_model('unidades', 'UnidadesMedicas')
    UnidadesMedicas.objects.bulk_create([
        UnidadesMedicas(nombre='Pediatría', descripcion='Atención médica para niños', planta='Primer piso'),
        UnidadesMedicas(nombre='Fractura', descripcion='Atención para lesiones óseas', planta='Segundo piso'),
        UnidadesMedicas(nombre='General', descripcion='Medicina general', planta='Planta baja'),
        UnidadesMedicas(nombre='Internista', descripcion='Especialistas en medicina interna', planta='Tercer piso'),
        UnidadesMedicas(nombre='Dermatólogo', descripcion='Especialistas en piel y afecciones dérmicas', planta='Segundo piso'),
    ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesMedicas',
            fields=[
                ('unidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('planta', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidad', to='usuarios.usuarios')),
            ],
        ),
        migrations.RunPython(unidades_medicas),
    ]
