# Generated by Django 5.2.1 on 2025-06-01 20:24

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.auth.hashers import make_password

def create_roles_and_users(apps, schema_editor):
    Roles = apps.get_model('usuarios', 'Roles')
    Usuarios = apps.get_model('usuarios', 'Usuarios')
    TipoAfiliacion = apps.get_model('pacientes', 'TipoAfiliacion')
    JornadasLaborales = apps.get_model('doctores', 'JornadasLaborales')

    # Crear roles primero
    paciente_role = Roles.objects.create(nombre='paciente', descripcion='Paciente del sistema')
    doctor_role = Roles.objects.create(nombre='doctor', descripcion='Doctor del sistema')
    admin_role = Roles.objects.create(nombre='admin', descripcion='Administrador del sistema')

    # Crear usuarios luego
    Usuarios.objects.bulk_create([
        Usuarios(
            identificacion='1234567890',
            password=make_password('paciente123'),
            primer_nombre='Stiven',
            primer_apellido='Amorocho',
            genero='M',
            email='stiven.amorocho@eps.com',
            direccion='Calle 123',
            telefono='3001234567',
            fecha_nacimiento='2005-01-01',
            fecha_ingreso='2025-01-01',
            afiliacion=TipoAfiliacion.objects.get(nombre='contributivo'),
            role=paciente_role,
            activo=True
        ),
        Usuarios(
            identificacion='123456789',
            password=make_password('doctor123'),
            primer_nombre='Osvaldo',
            primer_apellido='Ospino',
            genero='M',
            email='osvaldo.ospino@eps.com',
            direccion='Calle 456',
            telefono='3002345678',
            fecha_nacimiento='2003-05-05',
            especialidad='Pediatría',
            fecha_ingreso='2020-01-01',
            jornada=JornadasLaborales.objects.get(nombre='matinal'),
            role=doctor_role,
            activo=True
        ),
        Usuarios(
            identificacion='12345678',
            password=make_password('doctor123'),
            primer_nombre='Alex',
            primer_apellido='Diaz',
            genero='M',
            email='alex.diaz@eps.com',
            direccion='Calle 910',
            telefono='3004567890',
            fecha_nacimiento='2004-05-05',
            especialidad='General',
            fecha_ingreso='2022-01-01',
            jornada=JornadasLaborales.objects.get(nombre='vespertina'),
            role=doctor_role,
            activo=True
        ),
        Usuarios(
            identificacion='1234567',
            password=make_password('admin123'),
            primer_nombre='Jose',
            primer_apellido='Angarita',
            genero='M',
            email='jose.angarita@eps.com',
            direccion='Calle 789',
            telefono='3003456789',
            fecha_nacimiento='2005-12-12',
            role=admin_role,
            activo=True
        ),
    ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('afiliacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.tipoafiliacion')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctores.jornadaslaborales')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.roles')),
            ],
        ),
        migrations.RunPython(create_roles_and_users),
    ]
