# Generated by Django 5.2.1 on 2025-05-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_contrasena_usuario_password'),
        ('usuarios', '0004_auto_20250520_1949'),
    ]

    operations = [
    ]
