# Generated by Django 5.2.1 on 2025-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('cita_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('consulta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateField()),
                ('sintomas', models.CharField(max_length=255)),
                ('tratamiento', models.CharField(max_length=255)),
                ('recomendaciones', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
