# Generated by Django 5.2.1 on 2025-06-04 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('cita_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('atendida', 'Atendida'), ('no_atendida', 'No Atendida')], default='agendada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_doctor', to='usuarios.usuarios')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.unidadesmedicas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('consulta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateField()),
                ('sintomas', models.CharField(max_length=255)),
                ('tratamiento', models.CharField(max_length=255)),
                ('recomendaciones', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.citas')),
            ],
        ),
    ]
