# Generated by Django 5.2.1 on 2025-05-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='citas',
            fields=[
                ('cita_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateTimeField()),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.unidadades_medicas')),
            ],
        ),
        migrations.CreateModel(
            name='consultas',
            fields=[
                ('consulta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateTimeField()),
                ('sintomas', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.citas')),
            ],
        ),
    ]
