# Generated by Django 5.2.1 on 2025-05-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('unidades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.unidadesmedicas'),
        ),
        migrations.AddField(
            model_name='citas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='consultas',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.citas'),
        ),
    ]
