# Generated by Django 5.2.1 on 2025-05-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
        ('usuarios', '0002_usuarios_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_doctor', to='usuarios.usuarios'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to='usuarios.usuarios'),
        ),
    ]
