# Generated by Django 5.2.1 on 2025-05-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_citas_doctor_alter_citas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('atendida', 'Atendida'), ('no_atendida', 'No Atendida')], default='agendada', max_length=20),
        ),
    ]
